### ISSUE TITLE
Error on exporting "ModuleNotFoundError" 'onnxruntime'

### ISSUE THREAD

**Issue by plenet10** [rhasspy/piper-recording-studio#15]
Hi there,
When exporting, I get an error:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Plene\Desktop\Demo-speech\piper\piper-recording-studio-master\export_dataset\__main__.py", line 12, in <module>
    from .trim import trim_silence
  File "C:\Users\Plene\Desktop\Demo-speech\piper\piper-recording-studio-master\export_dataset\trim.py", line 5, in <module>
    from .vad import SileroVoiceActivityDetector
  File "C:\Users\Plene\Desktop\Demo-speech\piper\piper-recording-studio-master\export_dataset\vad.py", line 5, in <module>
    import onnxruntime
ModuleNotFoundError: No module named 'onnxruntime'
```
Are there any recommendations?

**Comment by plenet10** [comment]
I have installed pip recommendations for export, my pip list is:

As you can see, Onnxruntime is installed
```
aiofiles      23.2.1
blinker       1.5
click         8.1.7
colorama      0.4.6
coloredlogs   15.0.1
flatbuffers   23.5.26
h11           0.14.0
h2            4.1.0
hpack         4.0.0
humanfriendly 10.0
hypercorn     0.14.3
hyperframe    6.0.1
itsdangerous  2.1.2
Jinja2        3.1.2
MarkupSafe    2.1.3
mpmath        1.3.0
numpy         1.26.2
onnxruntime   1.16.3
packaging     23.2
pip           23.3.2
priority      2.0.0
protobuf      4.25.1
pyreadline3   3.4.1
quart         0.18.4
setuptools    65.5.0
sympy         1.12
toml          0.10.2
Werkzeug      2.3.7
wsproto       1.2.0
```

**Comment by plenet10** [comment]
The problem was that it was running with `python3` instead of `python` as the command....
