### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by LukasFrinn** [rhasspy/piper-recording-studio#3]
Is this error a problem? otherwise the application works for me

[2023-05-13 20:53:48 +0000] [1] [INFO] Running on http://0.0.0.0:8000 (CTRL + C to quit)
2023-05-13 22:53:48 INFO:hypercorn.error:Running on http://0.0.0.0:8000 (CTRL + C to quit)
2023-05-13 22:54:05 ERROR:__main__:404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2023-05-13 22:54:05 Traceback (most recent call last):
2023-05-13 22:54:05   File "/app/.venv/lib/python3.9/site-packages/quart/app.py", line 1673, in full_dispatch_request
2023-05-13 22:54:05     result = await self.dispatch_request(request_context)
2023-05-13 22:54:05   File "/app/.venv/lib/python3.9/site-packages/quart/app.py", line 1712, in dispatch_request
2023-05-13 22:54:05     self.raise_routing_exception(request_)
2023-05-13 22:54:05   File "/app/.venv/lib/python3.9/site-packages/quart/app.py", line 1179, in raise_routing_exception
2023-05-13 22:54:05     raise request.routing_exception
2023-05-13 22:54:05   File "/app/.venv/lib/python3.9/site-packages/quart/ctx.py", line 62, in match_request
2023-05-13 22:54:05     ) = self.url_adapter.match(  # type: ignore
2023-05-13 22:54:05   File "/app/.venv/lib/python3.9/site-packages/werkzeug/routing/map.py", line 652, in match
2023-05-13 22:54:05     raise NotFound() from None
2023-05-13 22:54:05 werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

**Comment by synesthesiam** [comment]
No, I think this has to do with the browser trying to load the favicon (which doesn't exist).
