### ISSUE TITLE
subprocess.CalledProcessError

### ISSUE THREAD

**Issue by Mezze99** [rhasspy/piper-recording-studio#9]
Unfortunately I'm running in an error while executing the last step:

`$ python -m export_dataset output/de-DE ./demo-text-to-speech`

ERROR:__main__:export_audio
Traceback (most recent call last):
  File "C:\Users\myuser\Documents\GitHub\piper-recording-studio\export_dataset\_main__.py", line 107, in __call_
    audio_16khz_bytes = subprocess.check_output(
  File "C:\Python310\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ffmpeg', '-i', 'output\\de-DE\\0000000001_0300000050_General\\0000000009.webm', '-f', 's16le', '-acodec', 'pcm_s16le', '-ac', '1', '-ar', '16000', 'pipe:']' returned non-zero exit status 3221225781.

Can somebody provide support? The ffmpeg.exe is stored in the base folder and all dependencies are installed as well.

**Comment by Mezze99** [comment]
fixed, you need the whole bin content not just the ffmpeg.exe
